### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by olivier-nexmo** [nexmo-community/deskmo#1]
In config>services.php in the nexmo section, the following lines are missing:

        'private_key' => env('NEXMO_PRIVATE_KEY'),
        'application_id' => env('NEXMO_APPLICATION_ID'),

As seen in Part 2 of the tutorial - https://laravel-news.com/text-speech-calls-laravel-nexmo

**Comment by mheap** [comment]
This is already in the post:

> To add support for voice calls, we need to update config/services.php and add private_key and application_id to the nexmo section:

```
'nexmo' => [
    'key' => env('NEXMO_KEY'),
    'secret' => env('NEXMO_SECRET'),
    'sms_from' => env('NEXMO_NUMBER'),
    'private_key' => env('NEXMO_PRIVATE_KEY'),
    'application_id' => env('NEXMO_APPLICATION_ID'),
],
```
